#include "Days.h"

int main()
{
	/*BENCHMARK_FUNCTION(1, 1);
	BENCHMARK_FUNCTION(1, 2);

	BENCHMARK_FUNCTION(2, 1);
	BENCHMARK_FUNCTION(2, 2);

	BENCHMARK_FUNCTION(3, 1);
	BENCHMARK_FUNCTION(3, 2);

	BENCHMARK_FUNCTION(4, 1);
	BENCHMARK_FUNCTION(4, 2);

	BENCHMARK_FUNCTION(5, 1);
	BENCHMARK_FUNCTION(5, 2);

	BENCHMARK_FUNCTION(6, 1);
	BENCHMARK_FUNCTION(6, 2);

	BENCHMARK_FUNCTION(7, 1);
	BENCHMARK_FUNCTION(7, 2);

	BENCHMARK_FUNCTION(8, 1);
	BENCHMARK_FUNCTION(8, 2);

	BENCHMARK_FUNCTION(9, 1);
	BENCHMARK_FUNCTION(9, 2);

	BENCHMARK_FUNCTION(10, 1);
	BENCHMARK_FUNCTION(10, 2);

	BENCHMARK_FUNCTION(11, 1);
	BENCHMARK_FUNCTION(11, 2);

	BENCHMARK_FUNCTION(12, 1);
	BENCHMARK_FUNCTION(12, 2);

	BENCHMARK_FUNCTION(13, 1);
	BENCHMARK_FUNCTION(13, 2);

	BENCHMARK_FUNCTION(14, 1);
	BENCHMARK_FUNCTION(14, 2);

	BENCHMARK_FUNCTION(15, 1);
	BENCHMARK_FUNCTION(15, 2);

	BENCHMARK_FUNCTION(16, 1);
	BENCHMARK_FUNCTION(16, 2);

	BENCHMARK_FUNCTION(17, 1);
	BENCHMARK_FUNCTION(17, 2);

	BENCHMARK_FUNCTION(18, 1);
	BENCHMARK_FUNCTION(18, 2);

	BENCHMARK_FUNCTION(19, 1);
	BENCHMARK_FUNCTION(19, 2);

	BENCHMARK_FUNCTION(20, 1);
	BENCHMARK_FUNCTION(20, 2);

	BENCHMARK_FUNCTION(21, 1);
	BENCHMARK_FUNCTION(21, 2);*/

	BENCHMARK_FUNCTION(22, 1);
	BENCHMARK_FUNCTION(22, 2);

	BENCHMARK_FUNCTION(23, 1);
	BENCHMARK_FUNCTION(23, 2);

	/*BENCHMARK_FUNCTION(24, 1);
	BENCHMARK_FUNCTION(24, 2);*/
}